# Generated by Django 5.1.6 on 2025-03-01 17:11

import juegos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos_app', '0002_juego_clasificacion_edad_juego_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='img',
            field=models.FileField(upload_to='juegos/', validators=[juegos_app.models.validate_image_extension]),
        ),
    ]
